Repository fack2/attention-training, pull requests merged in 2019-10, with the labels that each got.

#19 Setup files
  .gitignore
  client/.eslintrc
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Home/index.js
  client/src/components/index.js
  client/src/index.js
  package.json
  travis.yml
Labels: changes-requested

#24 #22 build server
  client/.eslintrc
  client/.eslintrc.json
  package-lock.json
  package.json
  server/app.js
  server/index.js
Labels: approved

#23 Button component related to #20
  client/package-lock.json
  client/package.json
  client/src/components/Home/index.js
  client/src/components/sharedComponent/Button/index.js
Labels: approved

#26 writing readme
  README.md
Labels: in progress

#30 button Component
  client/src/components/sharedComponent/Button/index.js
Labels: approved

#27 Back button
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Home/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/BackButton/BackIcon.js
  client/src/components/sharedComponent/BackButton/index.js
  client/src/index.js
Labels: approved

#37 ProgressBar
  client/src/components/Home/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/ProgressBar/index.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
Labels: approved

#31 Landing page related to #2
  client/src/App.js
  client/src/assets/homeBackground.png
  client/src/assets/logoWeb.png
  client/src/components/GlobalComponent/index.js
  client/src/components/Home/HomeStyledComponent.js
  client/src/components/Home/index.js
Labels: awaiting-review

#35 Button Component
  client/src/components/sharedComponent/Button/index.js
Labels: approved

#41 README
  README.md
Labels: approved

#42 Dashboard page
  client/src/assets/Vector.png
  client/src/assets/icon.png
  client/src/assets/icon2.png
  client/src/components/Dashboard/DashboardStyledComponent.js
  client/src/components/Dashboard/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/Button/index.js
Labels: approved

#38 creating circle-progessBar-pag #5
  client/.eslintrc.json
  client/src/App.js
  client/src/components/Card/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/CircleProgressBar/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
  client/src/components/sharedComponent/ProgressBar/index.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
Labels: approved

#43 Quiz page #4
  client/src/Questions.js
  client/src/components/Card/index.js
  client/src/components/Card/style.js
  client/src/components/Home/HomeStyledComponent.js
  client/src/components/Home/index.js
  client/src/components/QuizPage/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/BackButton/BackIcon.js
  client/src/components/sharedComponent/BackButton/index.js
  client/src/components/sharedComponent/Button/index.js
  client/src/components/sharedComponent/CircleProgressBar/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
  client/src/components/sharedComponent/ProgressBar/index.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
Labels: approved

#47 #7 creating results page
  client/src/assets/results.png
  client/src/components/Results/index.js
  client/src/components/Results/style.Results.js
  client/src/components/index.js
  client/src/components/resultsData.js
Labels: approved

#46 Skills component
  client/src/components/Dashboard/DashboardStyledComponent.js
  client/src/components/Skills/FilterStyledComponent.js
  client/src/components/Skills/SkillsStyledComponent.js
  client/src/components/Skills/index.js
  client/src/components/index.js
  client/src/data.js
Labels: approved

#51 quiz-instructions component #3
  client/src/assets/quizInst.png
  client/src/components/Card/index.js
  client/src/components/Card/style.js
  client/src/components/QuizInstructions/index.js
  client/src/components/QuizPage/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/Button/index.js
Labels: approved

#52 100 progress
  client/src/components/QuizPage/index.js
  client/src/components/sharedComponent/BackButton/BackIcon.js
  client/src/components/sharedComponent/BackButton/index.js
  client/src/components/sharedComponent/CircleProgressBar/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
Labels: approved

#48 create 404 not found page
  client/src/assets/page-not-found.jpg
  client/src/components/404NotFound/index.js
  client/src/components/404NotFound/style.NotFound.js
  client/src/components/index.js
Labels: approved

#53 Individual skill page
  client/package-lock.json
  client/package.json
  client/src/components/IndividualSkill/IndividualSkillStyledComponent.js
  client/src/components/IndividualSkill/index.js
  client/src/components/index.js
  client/src/data.js
Labels: approved

#55 add X-button in quiz page#54
  client/package-lock.json
  client/package.json
  client/src/components/QuizPage/closeButton.js
  client/src/components/QuizPage/index.js
  client/src/components/QuizPage/swalStyle.js
  client/src/components/sharedComponent/BackButton/index.js
Labels: approved

#57 resolved color mismatch in dashboard
  client/src/assets/AboutUs.png
  client/src/assets/Vector.png
  client/src/assets/restart.png
  client/src/components/Dashboard/DashboardStyledComponent.js
  client/src/components/Dashboard/index.js
Labels: approved

#65 Skills component #8
  client/src/data.js
Labels: approved

#61 Basic information
  client/src/Basic.js
  client/src/components/BasicInformation/BasicInformationStyledComponent.js
  client/src/components/BasicInformation/index.js
  client/src/components/index.js
Labels: approved

#60 aboutUs page #12
  client/src/components/AboutUs/index.js
  client/src/components/Dashboard/index.js
  client/src/components/QuizPage/index.js
  client/src/components/index.js
  client/src/components/sharedComponent/BackButton/BackIcon.js
Labels: awaiting-review

#63 improvement #62
  client/src/components/Dashboard/index.js
  client/src/components/QuizPage/index.js
  client/src/components/sharedComponent/Button/index.js
  client/src/components/sharedComponent/CircleProgressBar/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
Labels: approved

#44 Refactor readme #21
  README.md
  client/README.md
  package.json
Labels: approved, documentation

#58 create cards animation style
  client/src/components/404NotFound/style.NotFound.js
  client/src/components/Card/index.js
  client/src/components/Card/style.js
  client/src/components/Dashboard/index.js
  client/src/components/Home/HomeStyledComponent.js
  client/src/components/QuizInstructions/index.js
  client/src/components/QuizPage/index.js
  client/src/components/QuizPage/swalStyle.js
  client/src/components/Results/style.Results.js
  client/src/components/Skills/FilterStyledComponent.js
  client/src/components/Skills/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
Labels: approved

#75 create a progressive web application
  client/public/index.html
  client/public/manifest.json
  client/src/index.js
  client/src/serviceWorker.js
Labels: approved

#74 cal result #73
  client/src/components/QuizPage/index.js
  client/src/components/Results/index.js
  client/src/components/index.js
Labels: approved

#70 responsive style
  client/src/assets/Home.png
  client/src/components/404NotFound/index.js
  client/src/components/AboutUs/index.js
  client/src/components/BasicInformation/BasicInformationStyledComponent.js
  client/src/components/Card/style.js
  client/src/components/Dashboard/DashboardStyledComponent.js
  client/src/components/Dashboard/index.js
  client/src/components/GlobalComponent/index.js
  client/src/components/Home/HomeStyledComponent.js
  client/src/components/Home/index.js
  client/src/components/IndividualSkill/IndividualSkillStyledComponent.js
  client/src/components/IndividualSkill/index.js
  client/src/components/QuizInstructions/index.js
  client/src/components/Results/style.Results.js
  client/src/components/Skills/SkillsStyledComponent.js
  client/src/components/Skills/index.js
  client/src/components/sharedComponent/Button/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
  client/src/data.js
Labels: approved

#78 #71 adding custom fonts
  client/src/assets/fonts/HKGrotesk-Bold.woff
  client/src/assets/fonts/HKGrotesk-Regular.woff
  client/src/components/GlobalComponent/index.js
Labels: approved

#79 Refactor style
  client/src/Basic.js
  client/src/components/QuizInstructions/index.js
  client/src/components/Skills/SkillsStyledComponent.js
  client/src/data.js
Labels: approved

#83 add topUp button #81
  client/src/App.js
  client/src/components/sharedComponent/BackTop/index.js
Labels: awaiting-review, refactor

#85 skip button
  client/src/components/QuizInstructions/index.js
Labels: awaiting-review, refactor

#82 Refactor skills & dashboard & basic
  client/src/Basic.js
  client/src/components/BasicInformation/BasicInformationStyledComponent.js
  client/src/components/BasicInformation/index.js
  client/src/components/Dashboard/DashboardStyledComponent.js
  client/src/components/GlobalComponent/index.js
  client/src/components/IndividualSkill/IndividualSkillStyledComponent.js
  client/src/components/IndividualSkill/index.js
  client/src/components/Skills/FilterStyledComponent.js
  client/src/components/Skills/SkillsStyledComponent.js
  client/src/components/Skills/index.js
  client/src/data.js
Labels: approved, refactor

#87 Landing page
  client/src/components/Home/index.js
Labels: approved, refactor

#84 #81 add animation card and edit counter font
  client/package-lock.json
  client/package.json
  client/src/assets/confetti.gif
  client/src/components/QuizPage/index.js
  client/src/components/sharedComponent/CircleProgressBar/index.js
  client/src/components/sharedComponent/CircleProgressBar/style.CircleProgressBar.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
Labels: approved, refactor

#86 refactor-quiz #81
  client/src/components/Card/index.js
  client/src/components/Card/style.js
  client/src/components/GlobalComponent/index.js
  client/src/components/QuizInstructions/index.js
  client/src/components/QuizPage/index.js
  client/src/components/sharedComponent/BackButton/index.js
  client/src/components/sharedComponent/ProgressBar/index.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
Labels: approved, refactor

#88 #81 add random skills link and back button to results page
  client/src/components/BasicInformation/index.js
  client/src/components/Dashboard/index.js
  client/src/components/Results/index.js
  client/src/components/Results/style.Results.js
Labels: changes-requested, refactor

#90 dashbord button
  client/src/components/Dashboard/index.js
  client/src/components/QuizPage/index.js
  client/src/components/Results/index.js
  client/src/components/Results/style.Results.js
Labels: awaiting-review, refactor

#91 eddit Xbutton and backTopButton
  client/src/assets/topUp.png
  client/src/components/QuizPage/closeButton.js
  client/src/components/QuizPage/index.js
  client/src/components/sharedComponent/BackTop/index.js
  client/src/components/sharedComponent/ProgressBar/index.js
  client/src/components/sharedComponent/ProgressBar/style.ProgressBar.js
Labels: approved, refactor
